<?php

/**
 * @file
 * Primary hook implementations for Prisoner hub taxonomy sorting module.
 */

use Drupal\computed_taxonomy_child_count\Field\ComputedTaxonomyChildCount;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\node\Entity\Node;
use Drupal\node\NodeInterface;

/**
 * Implements hook_entity_base_field_info().
 *
 * Create the child_term_count base field.
 */
function computed_taxonomy_child_count_entity_base_field_info(\Drupal\Core\Entity\EntityTypeInterface $entity_type) {
  $fields = [];
  if ($entity_type->id() == 'taxonomy_term') {
    $fields['child_term_count'] = BaseFieldDefinition::create('integer')
      ->setLabel(t('Child term count'))
      ->setDescription(t('A count of the amount of child taxonomy terms.'))
      ->setReadOnly(TRUE)
      ->setComputed(TRUE)
      ->setClass(ComputedTaxonomyChildCount::class);
  }
  return $fields;
}

