#
# This override file contains build contexts and local mount points
# to enable local development.
#
# docker-compose.yml _AND_ docker-compose.override.yml are loaded by default
# so you don't need to specify this file manually.
#
# To explicitly ignore these overrides (e.g. to test the setup with no local mounts)
# use:
#
#   $ docker-compose -f docker-compose.yml <command>
#
services:
  drupal:
    build:
      target: local
    volumes:
      - .:/var/www/html
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.kube:/var/www/.kube
    env_file:
      - prisoner-content-hub-backend.env
      - prisoner-content-hub-backend-local.env
  localstack:
    volumes:
      - ./scripts/createLocalstackS3Bucket.sh:/docker-entrypoint-initaws.d/createLocalstackS3Bucket.sh
