version: "3"

services:
  prisoner-content-hub-backend-db:
    image: mariadb
    env_file:
      - prisoner-content-hub-backend-db.circleci.env
    ports:
      - 3306:3306
    networks:
      - circleci-prisoner_content_hub

  prisoner-content-hub-backend:
    image: mojdigitalstudio/prisoner-content-hub-backend
    build:
      context: .
      target: test
    depends_on:
      - prisoner-content-hub-backend-db
    env_file:
      - prisoner-content-hub-backend.circleci.env
    ports:
      - 11001:8080
    networks:
      - circleci-prisoner_content_hub
  chrome:
    image: previousnext/chrome-headless:65
    ports:
      - "${CHROMEDRIVER_PORT-9222}:9222"
    networks:
      - circleci-prisoner_content_hub

networks:
  circleci-prisoner_content_hub:
