FROM drupal:8.9-apache

# Install Composer and it's dependencies
RUN apt-get update && apt-get install -y \
  curl \
  git-core \
  mediainfo \
  unzip \
  && rm -rf /var/lib/apt/lists/*

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php --install-dir=/bin --filename=composer --version=1.10.16
RUN php -r "unlink('composer-setup.php');"

# Set Timezone
RUN echo "date.timezone = Europe/London" > /usr/local/etc/php/conf.d/timezone_set.ini

# Remove the memory limit for the CLI only.
RUN echo 'memory_limit = -1' > /usr/local/etc/php/php-cli.ini

# Remove the vanilla Drupal project that comes with this image.
RUN rm -rf ..?* .[!.]* *

# Install Drupal 8.x Dev
RUN composer create-project drupal-composer/drupal-project:8.x-dev . --stability dev --no-interaction

RUN composer require --dev \
  drupal/drupal-extension:^4.0

# Update autoloads
RUN composer dump-autoload --optimize

WORKDIR /opt/drupal/web

COPY phpunit.xml core/phpunit.xml

COPY modules/custom modules/custom

RUN ../vendor/bin/phpunit -c core --testsuite unit --debug --verbose
