version: "3"

services:
  prisoner-content-hub-backend-db:
    image: mariadb
    env_file:
      - prisoner-content-hub-backend-db.circleci.env
    ports:
      - 3306:3306
    networks:
      - circleci-prisoner_content_hub

  prisoner-content-hub-backend:
    image: mojdigitalstudio/prisoner-content-hub-backend
    build:
      context: .
      target: test
    depends_on:
      - prisoner-content-hub-backend-db
    env_file:
      - prisoner-content-hub-backend.circleci.env
    ports:
      - 11001:8080
    networks:
      - circleci-prisoner_content_hub

  prisoner-content-hub-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - circleci-prisoner_content_hub
  chrome:
    image: previousnext/chrome-headless:65
    ports:
      - "${CHROMEDRIVER_PORT-9222}:9222"
    networks:
      - circleci-prisoner_content_hub

  prisoner-content-hub-redis:
    image: redis:5.0.6
    ports:
      - 6379:6379
    networks:
      - circleci-prisoner_content_hub

networks:
  circleci-prisoner_content_hub:
