services:
  database:
    image: mariadb:10.11
    env_file:
      - prisoner-content-hub-backend-db.env
    ports:
      - 3306:3306
    networks:
      - prisoner_content_hub

  drupal:
    image: quay.io/hmpps/prisoner-content-hub-backend
    build:
      context: .
      target: test
    depends_on:
      - database
    env_file:
      - prisoner-content-hub-backend.env
    ports:
      - 11001:8080
    networks:
      - prisoner_content_hub

  opensearch:
    image: opensearchproject/opensearch:2.7.0
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - '9200:9200'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - prisoner_content_hub

  chrome:
    image: previousnext/chrome-headless:65
    ports:
      - "${CHROMEDRIVER_PORT-9222}:9222"
    networks:
      - prisoner_content_hub

  redis:
    image: redis:5.0.6
    ports:
      - 6379:6379
    networks:
      - prisoner_content_hub

  localstack:
    image: localstack/localstack:0.13.3
    environment:
      - SERVICES=s3
    ports:
      - "4566:4566"
    networks:
      - prisoner_content_hub


networks:
  prisoner_content_hub:
    name: prisoner_content_hub
