<?php

namespace Drupal\prisoner_hub_primary_nav\Resource;

use Drupal\jsonapi\ResourceResponse;
use Drupal\jsonapi_menu_items\Resource\MenuItemsResource;
use Drupal\system\MenuInterface;
use Drupal\taxonomy\TermInterface;
use Symfony\Component\HttpFoundation\Request;


/**
 * Processes a request for the primary navifation
 */
class PrimaryNavResource extends MenuItemsResource {

  public function process(Request $request, MenuInterface $menu = NULL): ResourceResponse {
    // $menu should always be NULL, as our route doesn't allow for a menu
    // parameter. We instead get the menu from the prison context.
    if (is_null($menu)) {
      $prison = \Drupal::routeMatch()->getParameter('prison');
      if ($prison instanceof TermInterface) {
        $entities = $prison->get('field_primary_navigation')->referencedEntities();
        if (!empty($entities)) {
          $menu = reset($entities);
        }
      }
    }
    return parent::process($request, $menu); // TODO: Change the autogenerated stub
  }

}
