defaults: &defaults
  working_directory: ~/workspace
  docker:
    - image: mojdigitalstudio/circleci-build-container
main_branch: &main_branch
  filters:
    branches:
      only: main
feature_branch: &feature_branch
  filters:
    branches:
      ignore: main

version: 2.1

orbs:
  kubernetes: circleci/kubernetes@0.3.0
  helm: circleci/helm@1.0.0

commands:
  release_to_namespace:
    description: "Release with Helm"
    parameters:
      environment:
        type: string
    steps:
      - kubernetes/install
      - helm/install-helm-client:
          version: v3.2.1
      - checkout:
          path: ~/git
      - attach_workspace:
          at: /tmp/build-info
      - run:
          name: Configure kubectl context
          command: |
            echo -n ${KUBE_CLUSTER_CERT} | base64 -d > /tmp/cluster-ca.crt
            kubectl config set-cluster ${KUBE_CLUSTER_NAME} \
              --certificate-authority=/tmp/cluster-ca.crt \
              --server="https://api.${KUBE_CLUSTER_NAME}"
            kubectl config set-credentials circleci \
              --token=${KUBE_TOKEN}
            kubectl config set-context ${KUBE_CLUSTER_NAME} \
              --cluster=${KUBE_CLUSTER_NAME} \
              --user=circleci \
              --namespace=${KUBE_NAMESPACE}
            kubectl config use-context ${KUBE_CLUSTER_NAME}
      - run:
          name: Release to << parameters.environment >>
          command: |
            VERSION_TO_DEPLOY=$(cat /tmp/build-info/version-to-deploy.txt)
            helm upgrade ${HELM_BACKEND_RELEASE_NAME} ~/git/helm_deploy/prisoner-content-hub-backend \
              --install --wait --force --reset-values --timeout 360s \
              --namespace=${KUBE_NAMESPACE} \
              --values ~/git/helm_deploy/prisoner-content-hub-backend/values.<< parameters.environment >>.yaml \
              --set image.tag=${VERSION_TO_DEPLOY} \
              --set cronToken=${HELM_BACKEND_CRON_TOKEN}

jobs:
  build_preview:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: make build
      - run:
          name: Push Docker image
          command: make push-preview
      - run:
          name: Persist build number for deployment
          command: |
            mkdir -p /tmp/build-info
            echo preview > /tmp/build-info/version-to-deploy.txt
      - persist_to_workspace:
          root: /tmp/build-info
          paths:
            - version-to-deploy.txt
  build_production:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: make build
      - run:
          name: Push Docker image
          command: make push
      - add_ssh_keys:
          fingerprints:
            - "43:37:0b:4a:c0:7a:20:72:bb:a4:92:c1:2f:9e:27:e7"
      - run:
          name: Create Git Tag
          command: |
            git config user.name "Circle CI"
            git config user.email "circle@circleci.com"
            git tag -a "$(date '+%Y-%m-%d').$CIRCLE_BUILD_NUM" $CIRCLE_SHA1 -m "$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=%B)"
            git push origin "$(date '+%Y-%m-%d').$CIRCLE_BUILD_NUM"
      - run:
          name: Persist build number for deployment
          command: |
            mkdir -p /tmp/build-info
            echo build-${CIRCLE_BUILD_NUM} > /tmp/build-info/version-to-deploy.txt
      - persist_to_workspace:
          root: /tmp/build-info
          paths:
            - version-to-deploy.txt

  deploy_cloud_platform_development:
    <<: *defaults
    steps:
      - release_to_namespace:
          environment: "development"

  deploy_cloud_platform_staging:
    <<: *defaults
    steps:
      - release_to_namespace:
          environment: "staging"

  deploy_cloud_platform_production:
    <<: *defaults
    steps:
      - release_to_namespace:
          environment: "production"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - approve_preview_build:
          <<: *feature_branch
          type: approval
      - build_preview:
          <<: *feature_branch
          requires:
            - approve_preview_build
      - build_production:
          <<: *main_branch

      - deploy_cloud_platform_development:
          <<: *main_branch
          context: prisoner-content-hub-development
          requires:
            - approve_preview_build

      - deploy_cloud_platform_staging:
          <<: *main_branch
          context: prisoner-content-hub-staging
          requires:
            - build_production

      - approve_deploy_production:
          <<: *main_branch
          type: approval
          requires:
            - deploy_cloud_platform_staging
      - deploy_cloud_platform_production:
          <<: *main_branch
          context: prisoner-content-hub-prod
          requires:
            - approve_deploy_production
