@prison = berwyn
@tag_id = 1535
@topic_uuid = ff43d107-d52c-47c9-8100-4fc5b3d148ef
@node_id = 4164
@video_uuid = 53cd415a-b831-4f4f-8fdf-64b9b15af863
@series_id = 871
@series_sort_value = -4002
@category_uuid = 7a80305b-9dcd-4030-9821-7b055a6462f8
@page_uuid = 7a80305b-9dcd-4030-9821-7b055a6462f8
@pdf_uuid = 569e381b-300f-487f-90f5-c433f3c3c4a8
@link_uuid = 8be7944d-db0a-431a-ae7e-c8d450ee332c
@radio_uuid = 02bb3b40-9d1a-4194-ad8c-1054b7b3b1d8
@search_text = prison
# English
@language =
# Welsh
#@language = /cy

###
# @name GetCategory
GET {{address}}{{language}}/jsonapi/prison/{{prison}}/taxonomy_term/moj_categories/{{category_uuid}}?
  include=field_featured_tiles%2Cfield_featured_tiles.field_moj_thumbnail_image&
  fields%5Bnode--page%5D=drupal_internal__nid%2Cdrupal_internal__tid%2Ctitle%2Cfield_moj_thumbnail_image%2Cfield_topics%2Cpath%2Cfield_exclude_feedback%2Cpublished_at&
  fields%5Bnode--moj_video_item%5D=drupal_internal__nid%2Cdrupal_internal__tid%2Ctitle%2Cfield_moj_thumbnail_image%2Cfield_topics%2Cpath%2Cfield_exclude_feedback%2Cpublished_at&
  fields%5Bnode--moj_radio_item%5D=drupal_internal__nid%2Cdrupal_internal__tid%2Ctitle%2Cfield_moj_thumbnail_image%2Cfield_topics%2Cpath%2Cfield_exclude_feedback%2Cpublished_at&
  fields%5Bmoj_pdf_item%5D=drupal_internal__nid%2Cdrupal_internal__tid%2Ctitle%2Cfield_moj_thumbnail_image%2Cfield_topics%2Cpath%2Cfield_exclude_feedback%2Cpublished_at&
  fields%5Btaxonomy_term_series%5D=drupal_internal__nid%2Cdrupal_internal__tid%2Ctitle%2Cfield_moj_thumbnail_image%2Cfield_topics%2Cpath%2Cfield_exclude_feedback%2Cpublished_at&
  fields%5Btaxonomy_term--moj_categories%5D=name%2Cdescription%2Cfield_exclude_feedback%2Cfield_featured_tiles%2Cbreadcrumbs%2Cchild_term_count

> test_cache_hit.js

###
# @name NodeIdToUuid
GET {{address}}/router/prison/{{prison}}/translate-path?
  path=content/{{node_id}}

> test_cache_hit.js

###
# @name TermIdToUuid
GET {{address}}/router/prison/{{prison}}/translate-path?
  path=tags/{{tag_id}}

> test_cache_hit.js

###
# @name Homepage
GET {{address}}{{language}}/jsonapi/prison/{{prison}}/node/homepage?
  include=field_featured_tiles.field_moj_thumbnail_image%2Cfield_featured_tiles%2Cfield_large_update_tile%2Cfield_key_info_tiles%2Cfield_key_info_tiles.field_moj_thumbnail_image%2Cfield_large_update_tile.field_moj_thumbnail_image%2Cfield_featured_tiles.field_image.field_media_image&
  page%5Blimit%5D=4&
  fields%5Bnode--field_featured_tiles%5D=drupal_internal__nid%2Ctitle%2Cfield_moj_thumbnail_image%2Cfield_summary%2Cfield_moj_series%2Cpath%2Ctype.meta.drupal_internal__target_id%2Cpublished_at&
  fields%5Bnode--field_key_info_tiles%5D=drupal_internal__nid%2Ctitle%2Cfield_moj_thumbnail_image%2Cfield_summary%2Cfield_moj_series%2Cpath%2Ctype.meta.drupal_internal__target_id%2Cpublished_at&
  fields%5Bfile--file%5D=drupal_internal__fid%2Cid%2Cimage_style_uri

> test_cache_hit.js

###
# @name HomePageExploreTheHub
GET {{address}}{{language}}/jsonapi/prison/{{prison}}/explore/node?
  include=field_moj_thumbnail_image&
  page%5Blimit%5D=4&
  fields%5Bnode--page%5D=drupal_internal__nid%2Ctitle%2Cfield_moj_thumbnail_image%2Cfield_summary%2Cfield_moj_series%2Cpath%2Ctype.meta.drupal_internal__target_id%2Cpublished_at&
  fields%5Bnode--moj_video_item%5D=drupal_internal__nid%2Ctitle%2Cfield_moj_thumbnail_image%2Cfield_summary%2Cfield_moj_series%2Cpath%2Ctype.meta.drupal_internal__target_id%2Cpublished_at&
  fields%5Bnode--moj_radio_item%5D=drupal_internal__nid%2Ctitle%2Cfield_moj_thumbnail_image%2Cfield_summary%2Cfield_moj_series%2Cpath%2Ctype.meta.drupal_internal__target_id%2Cpublished_at&
  fields%5Bnode--moj_pdf_item%5D=drupal_internal__nid%2Ctitle%2Cfield_moj_thumbnail_image%2Cfield_summary%2Cfield_moj_series%2Cpath%2Ctype.meta.drupal_internal__target_id%2Cpublished_at

> test_cache_hit.js

###
# @name HomePageRecentlyAdded
GET {{address}}{{language}}/jsonapi/prison/{{prison}}/recently-added?
  include=field_moj_thumbnail_image&
  sort=-published_at%2Ccreated&
  fields%5Bnode--page%5D=drupal_internal__nid%2Ctitle%2Cfield_moj_thumbnail_image%2Cfield_summary%2Cfield_moj_series%2Cpath%2Ctype.meta.drupal_internal__target_id%2Cpublished_at&
  fields%5Bnode--moj_video_item%5D=drupal_internal__nid%2Ctitle%2Cfield_moj_thumbnail_image%2Cfield_summary%2Cfield_moj_series%2Cpath%2Ctype.meta.drupal_internal__target_id%2Cpublished_at&
  fields%5Bnode--moj_radio_item%5D=drupal_internal__nid%2Ctitle%2Cfield_moj_thumbnail_image%2Cfield_summary%2Cfield_moj_series%2Cpath%2Ctype.meta.drupal_internal__target_id%2Cpublished_at&
  fields%5Bnode--moj_pdf_item%5D=drupal_internal__nid%2Ctitle%2Cfield_moj_thumbnail_image%2Cfield_summary%2Cfield_moj_series%2Cpath%2Ctype.meta.drupal_internal__target_id%2Cpublished_at&
  fields%5Bfile--file%5D=drupal_internal__fid%2Cid%2Cimage_style_uri&
  page[offset]=0&
  page[limit]=8

> test_cache_hit.js

###
# @name HomePageUpdates
GET {{address}}{{language}}/jsonapi/prison/{{prison}}/node?
  filter%5B6%5D%5Bcondition%5D%5Bpath%5D=published_at&
  filter%5B6%5D%5Bcondition%5D%5Bvalue%5D=1723192942&
  filter%5B6%5D%5Bcondition%5D%5Boperator%5D=%3E%3D&
  filter%5B6%5D%5Bcondition%5D%5BmemberOf%5D=series_group&
  filter%5Bparent_or_group%5D%5Bgroup%5D%5Bconjunction%5D=OR&
  filter%5Bcategories_group%5D%5Bgroup%5D%5Bconjunction%5D=AND&
  filter%5Bcategories_group%5D%5Bgroup%5D%5BmemberOf%5D=parent_or_group&
  filter%5Bseries_group%5D%5Bgroup%5D%5Bconjunction%5D=AND&
  filter%5Bseries_group%5D%5Bgroup%5D%5BmemberOf%5D=parent_or_group&
  filter%5Bfield_moj_top_level_categories.field_is_homepage_updates%5D%5Bcondition%5D%5Bpath%5D=field_moj_top_level_categories.field_is_homepage_updates&
  filter%5Bfield_moj_top_level_categories.field_is_homepage_updates%5D%5Bcondition%5D%5Bvalue%5D=1&
  filter%5Bfield_moj_top_level_categories.field_is_homepage_updates%5D%5Bcondition%5D%5BmemberOf%5D=categories_group&
  filter%5Bpublished_at%5D%5Bcondition%5D%5Bpath%5D=published_at&
  filter%5Bpublished_at%5D%5Bcondition%5D%5Bvalue%5D=1723192942&
  filter%5Bpublished_at%5D%5Bcondition%5D%5Boperator%5D=%3E%3D&
  filter%5Bpublished_at%5D%5Bcondition%5D%5BmemberOf%5D=categories_group&
  filter%5Bfield_moj_series.field_is_homepage_updates%5D%5Bcondition%5D%5Bpath%5D=field_moj_series.field_is_homepage_updates&
  filter%5Bfield_moj_series.field_is_homepage_updates%5D%5Bcondition%5D%5Bvalue%5D=1&
  filter%5Bfield_moj_series.field_is_homepage_updates%5D%5Bcondition%5D%5BmemberOf%5D=series_group&
  include=field_moj_thumbnail_image&
  sort=-published_at%2Ccreated&
  fields%5Bnode--page%5D=drupal_internal__nid%2Ctitle%2Cfield_moj_thumbnail_image%2Cfield_summary%2Cfield_moj_series%2Cpath%2Ctype.meta.drupal_internal__target_id%2Cpublished_at&
  fields%5Bnode--moj_video_item%5D=drupal_internal__nid%2Ctitle%2Cfield_moj_thumbnail_image%2Cfield_summary%2Cfield_moj_series%2Cpath%2Ctype.meta.drupal_internal__target_id%2Cpublished_at&
  fields%5Bnode--moj_radio_item%5D=drupal_internal__nid%2Ctitle%2Cfield_moj_thumbnail_image%2Cfield_summary%2Cfield_moj_series%2Cpath%2Ctype.meta.drupal_internal__target_id%2Cpublished_at&
  fields%5Bnode--moj_pdf_item%5D=drupal_internal__nid%2Ctitle%2Cfield_moj_thumbnail_image%2Cfield_summary%2Cfield_moj_series%2Cpath%2Ctype.meta.drupal_internal__target_id%2Cpublished_at&
  fields%5Bfile--file%5D=drupal_internal__fid%2Cid%2Cimage_style_uri&
  page[offset]=0&
  page[limit]=5

> test_cache_hit.js

###
# @name Link
GET {{address}}{{language}}/jsonapi/prison/{{prison}}/node/link/{{link_uuid}}?
  fields%5Bnode--link%5D=title%2Cdrupal_internal__nid%2Cfield_show_interstitial_page%2Cfield_url

> test_cache_hit.js

###
# @name NextInSeries
GET {{address}}{{language}}/jsonapi/prison/{{prison}}/node?
  filter%5Bfield_moj_series.meta.drupal_internal__tid%5D={{series_id}}&
  filter%5Bnext_items%5D%5Bgroup%5D%5Bconjunction%5D=OR&
  filter%5Bseries_sort_value%5D%5Bcondition%5D%5Bpath%5D=series_sort_value&
  filter%5Bseries_sort_value%5D%5Bcondition%5D%5Bvalue%5D={{series_sort_value}}&
  filter%5Bseries_sort_value%5D%5Bcondition%5D%5Boperator%5D=%3E&
  filter%5Bseries_sort_value%5D%5Bcondition%5D%5BmemberOf%5D=next_items&
  filter%5Bcreated%5D%5Bcondition%5D%5Bpath%5D=created&
  filter%5Bcreated%5D%5Bcondition%5D%5Boperator%5D=%3E&
  filter%5Bcreated%5D%5Bcondition%5D%5BmemberOf%5D=next_items&
  include=field_moj_thumbnail_image&
  page%5Blimit%5D=3&
  sort=series_sort_value%2Ccreated&
  fields%5Bnode--page%5D=drupal_internal__nid%2Cfield_moj_episode%2Ctitle%2Cfield_moj_season%2Cfield_moj_series%2Cseries_sort_value%2Cfield_moj_thumbnail_image&
  fields%5Bnode--moj_video_item%5D=drupal_internal__nid%2Cfield_moj_episode%2Ctitle%2Cfield_moj_season%2Cfield_moj_series%2Cseries_sort_value%2Cfield_moj_thumbnail_image&
  fields%5Bnode--moj_radio_item%5D=drupal_internal__nid%2Cfield_moj_episode%2Ctitle%2Cfield_moj_season%2Cfield_moj_series%2Cseries_sort_value%2Cfield_moj_thumbnail_image&
  fields%5Bnode--moj_pdf_item%5D=drupal_internal__nid%2Cfield_moj_episode%2Ctitle%2Cfield_moj_season%2Cfield_moj_series%2Cseries_sort_value%2Cfield_moj_thumbnail_image&
  fields%5Bfile--file%5D=uri%2Cimage_style_uri

> test_cache_hit.js

###
# @name NodesInCategory
GET {{address}}{{language}}/jsonapi/prison/{{prison}}/node?
  filter%5Bfield_moj_top_level_categories.id%5D={{category_uuid}}&
  include=field_moj_thumbnail_image%2Cfield_image&
  sort=-created&
  fields%5Bnode--page%5D=drupal_internal__nid%2Ctitle%2Cfield_summary%2Cfield_moj_thumbnail_image%2Cpath%2Cpublished_at&
  fields%5Bnode--moj_video_item%5D=drupal_internal__nid%2Ctitle%2Cfield_summary%2Cfield_moj_thumbnail_image%2Cpath%2Cpublished_at&
  fields%5Bnode--moj_radio_item%5D=drupal_internal__nid%2Ctitle%2Cfield_summary%2Cfield_moj_thumbnail_image%2Cpath%2Cpublished_at&
  fields%5Bmoj_pdf_item%5D=drupal_internal__nid%2Ctitle%2Cfield_summary%2Cfield_moj_thumbnail_image%2Cpath%2Cpublished_at&
  page[offset]=0&
  page[limit]=40

> test_cache_hit.js

###
# @name NodesInTopic
GET {{address}}{{language}}/jsonapi/prison/{{prison}}/node?
  filter%5Bfield_topics.id%5D={{topic_uuid}}&
  include=field_moj_thumbnail_image%2Cfield_topics.field_moj_thumbnail_image&
  sort=-created&
  fields%5Bnode--page%5D=drupal_internal__nid%2Ctitle%2Cfield_summary%2Cfield_moj_thumbnail_image%2Cfield_topics%2Cpath%2Cpublished_at&
  fields%5Bnode--moj_video_item%5D=drupal_internal__nid%2Ctitle%2Cfield_summary%2Cfield_moj_thumbnail_image%2Cfield_topics%2Cpath%2Cpublished_at&
  fields%5Bnode--moj_radio_item%5D=drupal_internal__nid%2Ctitle%2Cfield_summary%2Cfield_moj_thumbnail_image%2Cfield_topics%2Cpath%2Cpublished_at&
  fields%5Bnode--moj_pdf_item%5D=drupal_internal__nid%2Ctitle%2Cfield_summary%2Cfield_moj_thumbnail_image%2Cfield_topics%2Cpath%2Cpublished_at&
  fields%5Bfile--file%5D=image_style_uri&
  fields%5Btaxonomy_term--topics%5D=name%2Cdescription%2Cdrupal_internal__tid%2Cfield_moj_thumbnail_image%2Cpath%2Cfield_exclude_feedback%2Cbreadcrumbs&
  page[offset]=0&
  page[limit]=40

> test_cache_hit.js

###
# @name Page
GET {{address}}{{language}}/jsonapi/prison/{{prison}}/node/page/{{page_uuid}}?
  include=field_topics%2Cfield_moj_top_level_categories&
  fields%5Bnode--page%5D=drupal_internal__nid%2Ctitle%2Ccreated%2Cfield_main_body_content%2Cfield_moj_stand_first%2Cfield_topics%2Cfield_moj_series%2Cfield_moj_top_level_categories%2Cfield_exclude_feedback%2Cbreadcrumbs&
  fields%5Btaxonomy_term--topics%5D=drupal_internal__tid%2Cname&
  fields%5Btaxonomy_term--moj_categories%5D=drupal_internal__tid%2Cname

> test_cache_hit.js

###
# @name Pdf
GET {{address}}{{language}}/jsonapi/prison/{{prison}}/node/moj_pdf_item/{{pdf_uuid}}?
  include=field_moj_pdf&
  fields%5Bnode--moj_pdf_item%5D=drupal_internal__nid%2Ctitle%2Cfield_moj_pdf

> test_cache_hit.js

###
# @name PrimaryNavigation
GET {{address}}{{language}}/jsonapi/prison/{{prison}}/primary_navigation?
  fields%5Bmenu_link_content--menu_link_content%5D=id%2Ctitle%2Curl

> test_cache_hit.js

###
# @name Radio
GET {{address}}{{language}}/jsonapi/prison/{{prison}}/node/moj_radio_item/{{radio_uuid}}?
  include=field_moj_thumbnail_image%2Cfield_moj_series%2Cfield_moj_audio%2Cfield_topics%2Cfield_moj_top_level_categories&
  fields%5Bnode--moj_radio_item%5D=drupal_internal__nid%2Ctitle%2Ccreated%2Cfield_moj_audio%2Cfield_description%2Cfield_topics%2Cfield_moj_series%2Cfield_moj_season%2Cfield_moj_episode%2Cfield_moj_top_level_categories%2Cfield_moj_thumbnail_image%2Cfield_moj_programme_code%2Cseries_sort_value%2Cfield_exclude_feedback%2Cbreadcrumbs&
  fields%5Bfile--file%5D=uri%2Cimage_style_uri&
  fields%5Btaxonomy_term--series%5D=drupal_internal__tid%2Cname%2Cpath&
  fields%5Btaxonomy_term--topics%5D=drupal_internal__tid%2Cname%2Cpath&
  fields%5Btaxonomy_term--moj_categories%5D=drupal_internal__tid%2Cname

> test_cache_hit.js

###
# @name SubtermsForCategory
GET {{address}}{{language}}/jsonapi/prison/{{prison}}/taxonomy_term/moj_categories/{{category_uuid}}/sub_terms?
  include=field_moj_thumbnail_image&
  fields%5Btaxonomy_term--series%5D=type%2Cdrupal_internal__tid%2Cname%2Cfield_moj_thumbnail_image%2Cpath%2Ccontent_updated%2Cchild_term_count%2Cpublished_at&
  fields%5Btaxonomy_term--moj_categories%5D=type%2Cdrupal_internal__tid%2Cname%2Cfield_moj_thumbnail_image%2Cpath%2Ccontent_updated%2Cchild_term_count%2Cpublished_at&
  page[offset]=0&
  page[limit]=40

> test_cache_hit.js

###
# @name Topics
GET {{address}}{{language}}/jsonapi/prison/{{prison}}/taxonomy_term?
  filter%5Bvid.meta.drupal_internal__target_id%5D=topics&
  page%5Blimit%5D=100&
  sort=name&
  fields%5Btaxonomy_term--topics%5D=drupal_internal__tid%2Cname

> test_cache_hit.js

###
# @name UrgentBanners
GET {{address}}{{language}}/jsonapi/prison/{{prison}}/node/urgent_banner?
  include=field_more_info_page&
  fields%5Bnode--urgent_banner%5D=drupal_internal__nid%2Ctitle%2Ccreated%2Cchanged%2Cfield_more_info_page%2Cunpublish_on

> test_cache_hit.js

###
# @name Video
GET {{address}}{{language}}/jsonapi/prison/{{prison}}/node/moj_video_item/{{video_uuid}}?
  include=field_moj_thumbnail_image%2Cfield_moj_series%2Cfield_video%2Cfield_topics%2Cfield_moj_top_level_categories&
  fields%5Bnode--moj_video_item%5D=drupal_internal__nid%2Ctitle%2Ccreated%2Cfield_video%2Cfield_description%2Cfield_topics%2Cfield_moj_series%2Cfield_moj_season%2Cfield_moj_episode%2Cfield_moj_top_level_categories%2Cfield_moj_thumbnail_image%2Cseries_sort_value%2Cfield_exclude_feedback%2Cbreadcrumbs&
  fields%5Bfile--file%5D=uri%2Cimage_style_uri&
  fields%5Btaxonomy_term--series%5D=drupal_internal__tid%2Cname%2Cpath&
  fields%5Btaxonomy_term--topics%5D=drupal_internal__tid%2Cname%2Cpath&
  fields%5Btaxonomy_term--moj_categories%5D=drupal_internal__tid%2Cname

> test_cache_hit.js

###
# @name YouMightLike
## This suggestions call was actually generated from a video item.
## Need to investigate why this uses a moj_radio_item path.
GET {{address}}{{language}}/jsonapi/prison/{{prison}}/node/moj_radio_item/{{video_uuid}}/suggestions?
  include=field_moj_thumbnail_image&
  page%5Blimit%5D=4&
  fields%5Bnode--page%5D=drupal_internal__nid%2Ctitle%2Cfield_summary%2Cfield_moj_thumbnail_image%2Cpath%2Cpublished_at&
  fields%5Bnode--moj_video_item%5D=drupal_internal__nid%2Ctitle%2Cfield_summary%2Cfield_moj_thumbnail_image%2Cpath%2Cpublished_at&
  fields%5Bnode--moj_radio_item%5D=drupal_internal__nid%2Ctitle%2Cfield_summary%2Cfield_moj_thumbnail_image%2Cpath%2Cpublished_at&
  fields%5Bnode--moj_pdf_item%5D=drupal_internal__nid%2Ctitle%2Cfield_summary%2Cfield_moj_thumbnail_image%2Cpath%2Cpublished_at&
  fields%5Bfile--file%5D=image_style_uri

> test_cache_hit.js

###
# @name SearchSuggestions
GET {{address}}{{language}}/jsonapi/prison/{{prison}}/index/content_for_search?filter%5Bfulltext%5D={{search_text}}&page%5Blimit%5D=5

> test_cache_hit.js

###
# @name SearchResults
GET {{address}}{{language}}/jsonapi/prison/{{prison}}/index/content_for_search?filter%5Bfulltext%5D={{search_text}}&page%5Blimit%5D=15

> test_cache_hit.js

###
# @name Playing with media
GET {{address}}{{language}}/jsonapi/prison/{{prison}}/node/page/{{page_uuid}}

###
# @name Playing with media - this just gets a page
GET {{address}}{{language}}/jsonapi/prison/{{prison}}/node/page/457141ba-0550-4f39-9526-e6be5ddc07e1

###
# @name Playing with media including the image - this is enough to get the uri to the image style
GET {{address}}{{language}}/jsonapi/prison/{{prison}}/node/page/457141ba-0550-4f39-9526-e6be5ddc07e1?
  include=field_moj_thumbnail_image

###
# @name Playing with media including the media field
GET {{address}}{{language}}/jsonapi/prison/{{prison}}/node/page/457141ba-0550-4f39-9526-e6be5ddc07e1?
  include=field_image

###
# @name Playing with media including the media field
GET {{address}}{{language}}/jsonapi/prison/{{prison}}/node/page/457141ba-0550-4f39-9526-e6be5ddc07e1?
  include=field_image.field_media_image
