<?php

/**
 * @file
 * Primary hook implementations for Prisoner hub entity access module.
 */


/**
 * Implements hook_search_api_query_alter().
 */
function prisoner_hub_prison_access_search_api_query_alter(\Drupal\search_api\Query\QueryInterface $query) {
 \Drupal::service('prisoner_hub_prison_access.search_api_query_alter')->searchApiQueryAlter($query);
}

/**
 * Implements hook_entity_access().
 */
function prisoner_hub_prison_access_entity_access(\Drupal\Core\Entity\EntityInterface $entity, $operation, \Drupal\Core\Session\AccountInterface $account) {
  return \Drupal::service('prisoner_hub_prison_access.entity_access_check')->checkAccess($entity);
}
