name: 'Configuration Manager'
type: module
description: 'Allows administrators to manage configuration changes.'
package: Core
# version: VERSION
# core: 8.x
configure: config.sync

# Information added by Drupal.org packaging script on 2018-04-25
version: '8.5.3'
core: '8.x'
project: 'drupal'
datestamp: 1524673226
