<?php

/**
 * @file
 * Contains jsonapi_filter_cache_tags.module.
 */

use Drupal\Core\Entity\ContentEntityInterface;

/**
 * Implements hook_entity_insert().
 */
function jsonapi_filter_cache_tags_entity_insert(\Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity instanceof ContentEntityInterface) {
    \Drupal::service('jsonapi_filter_cache_tags.cache_tags_builder')->invalidateForEntity($entity);
  }
}

/**
 * Implements hook_entity_update().
 */
function jsonapi_filter_cache_tags_entity_update(\Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity instanceof ContentEntityInterface) {
    \Drupal::service('jsonapi_filter_cache_tags.cache_tags_builder')->invalidateForEntity($entity);
  }
}
