<?php

/**
 * @file
 * Primary hook implementations for Prisoner hub sub terms module.
 */

/**
 * Implements hook_entity_update().
 */
function prisoner_hub_sub_terms_entity_update(\Drupal\Core\Entity\EntityInterface $entity) {
  \Drupal::service('prisoner_hub_sub_terms.cachetag_invalidator')->invalidate($entity, FALSE);
}

/**
 * Implements hook_entity_insert().
 */
function prisoner_hub_sub_terms_entity_insert(\Drupal\Core\Entity\EntityInterface $entity) {
  \Drupal::service('prisoner_hub_sub_terms.cachetag_invalidator')->invalidate($entity, TRUE);
}
