<?php

/**
 * @file
 * Contains prisoner_hub_category_taxonomy.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_field_group_form_process_build_alter().
 *
 * Add visible and required states to series and category fields.
 * Dependent on whether field_not_in_series has been ticked.
 */
function prisoner_hub_category_taxonomy_field_group_form_process_build_alter(array &$element, FormStateInterface $form_state, &$complete_form) {
  if (isset($element['group_series'])) {
    $element['group_category']['#states']['visible'][':input[name="field_not_in_series[value]"]']['checked'] = TRUE;
    $element['field_moj_top_level_categories']['widget']['#states']['required'][':input[name="field_not_in_series[value]"]']['checked'] = TRUE;
    $element['field_moj_series']['#states']['visible'][':input[name="field_not_in_series[value]"]']['checked'] = FALSE;
    $element['field_moj_series']['widget']['#states']['required'][':input[name="field_not_in_series[value]"]']['checked'] = FALSE;
    $element['group_season_and_episode_number']['#states']['visible'][':input[name="field_not_in_series[value]"]']['checked'] = FALSE;
    $element['group_release_date']['#states']['visible'][':input[name="field_not_in_series[value]"]']['checked'] = FALSE;
  }
}

/**
 * Implements hook_entity_presave().
 *
 * Clear out series/category data
 */
function prisoner_hub_category_taxonomy_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity instanceof NodeInterface && $entity->hasField('field_not_in_series')) {
    if ($entity->field_not_in_series->value) {
      $entity->set('field_moj_series', NULL);
      $entity->set('field_moj_episode', NULL);
      $entity->set('field_moj_season', NULL);
      $entity->set('field_release_date', NULL);
    }
    else {
      $entity->set('field_moj_top_level_categories', NULL);
    }
  }
}
