image:
  pullPolicy: Always

ingress:
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: prisoner-content-hub-backend-ingress-prisoner-content-hub-development-green
  hosts:
    - host: cms-prisoner-content-hub-development.apps.live.cloud-platform.service.justice.gov.uk
  jsonapi:
    annotations:
      external-dns.alpha.kubernetes.io/set-identifier: prisoner-content-hub-backend-jsonapi-ingress-prisoner-content-hub-development-green
    hosts:
      - host: jsonapi-cms-prisoner-content-hub-development.apps.live.cloud-platform.service.justice.gov.uk
dbRefresh:
  enabled: true
s3Sync:
  enabled: true
# Temporary switch for syncing new bucket from staging.
s3SyncTemp:
  enabled: true

# Uncomment this section to switch Drupal to use the new S3 bucket.
#application:
#  s3:
#    secretName: drupal-s3-2

# Temporary setting for passing new S3 bucket details to cron jobs.
application:
  s3-2:
    secretName: drupal-s3-2
