ingress:
  hostName: cms-prisoner-content-hub-development.apps.live-1.cloud-platform.service.justice.gov.uk
  hosts:
    - host: cms-prisoner-content-hub-development.apps.live-1.cloud-platform.service.justice.gov.uk
