ingress:
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: prisoner-content-hub-backend-prisoner-content-hub-production-blue
  hosts:
    - host: manage.content-hub.prisoner.service.justice.gov.uk
      cert_secret: prisoner-content-hub-cms-certificate
    - host: cms-prisoner-content-hub-production.apps.live-1.cloud-platform.service.justice.gov.uk
  hosts_jsonapi:
    - host: jsonapi-cms-prisoner-content-hub-production.apps.live-1.cloud-platform.service.justice.gov.uk

application:
  # The S3 bucket for production exists in Ireland,
  # but the default is London
  s3:
    region: eu-west-1
