image:
  pullPolicy: Always

ingress:
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: prisoner-content-hub-backend-prisoner-content-hub-development-green

  hosts:
    - host: cms-prisoner-content-hub-development.apps.live.cloud-platform.service.justice.gov.uk
  hosts_jsonapi:
    - host: jsonapi-cms-prisoner-content-hub-development.apps.live.cloud-platform.service.justice.gov.uk
