environmentName: production
ingress:
  hosts:
    - host: manage.content-hub.prisoner.service.justice.gov.uk
      cert_secret: prisoner-content-hub-cms-certificate
    - host: cms-prisoner-content-hub-production.apps.live.cloud-platform.service.justice.gov.uk
  jsonapi:
    hosts:
      - host: jsonapi-cms-prisoner-content-hub-production.apps.live.cloud-platform.service.justice.gov.uk

application:
  # The S3 bucket for production exists in Ireland,
  # but the default is London
  s3:
    region: eu-west-1

dbBackup:
  enabled: true
dbRefresh:
  enabled: false
