image:
  pullPolicy: Always
environmentName: development
ingress:
  hosts:
      - host: cms-prisoner-content-hub-development.apps.live.cloud-platform.service.justice.gov.uk
  jsonapi:
    hosts:
      - host: jsonapi-cms-prisoner-content-hub-development.apps.live.cloud-platform.service.justice.gov.uk
dbRefresh:
  enabled: true
