image:
  pullPolicy: Always

ingress:
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: prisoner-content-hub-backend-ingress-prisoner-content-hub-development-green
  hosts:
    - host: cms-prisoner-content-hub-development.apps.live.cloud-platform.service.justice.gov.uk
  jsonapi:
    annotations:
      external-dns.alpha.kubernetes.io/set-identifier: prisoner-content-hub-backend-jsonapi-ingress-prisoner-content-hub-development-green
    hosts:
      - host: jsonapi-cms-prisoner-content-hub-development.apps.live.cloud-platform.service.justice.gov.uk
dbRefresh:
  enabled: false
s3Sync:
  enabled: true
application:
  s3:
    secretName: drupal-s3-2
  analyticsSiteId: G-0RBPFCWD3X
