nameOverride: ""
fullnameOverride: ""

replicaCount: 3
maxReplicaCount: 6

image:
  repository: mojdigitalstudio/prisoner-content-hub-backend
  pullPolicy: IfNotPresent
  tag: latest

tier: backend

application:
  port: 8080
  liveness:
    endpoint: /api/health
    delaySeconds: 10
    timeoutSeconds: 10
  readiness:
    endpoint: /api/health
    delaySeconds: 10
    timeoutSeconds: 5
  config:
    phpMemoryLimit: 256M
    phpUploadMaxFileSize: 500M
    phpPostMaxSize: 500M
    xDebugIp: 127.0.0.1
    elasticsearchCluster: elasticsearch
    elasticsearchServiceName: aws-es-proxy-service
  dbSecretName: drupal-rds
  s3SecretName: drupal-s3
  s3Region: eu-west-2

volumes:
  - name: apache-cache
    emptyDir: {}

imagePullSecrets: [] # Are we using ECR?

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 33
  runAsGroup: 33

resources: {}

affinity: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  tlsEnabled: false
  path: /
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      Include /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf
      SecRuleEngine On
