nameOverride: ""
fullnameOverride: ""

replicaCount: 3
maxReplicaCount: 6

image:
  repository: mojdigitalstudio/prisoner-content-hub-backend
  pullPolicy: IfNotPresent
  tag: latest

tier: backend

application:
  port: 8080
  liveness:
    endpoint: /
    delaySeconds: 10
    timeoutSeconds: 10
  readiness:
    endpoint: /
    delaySeconds: 10
    timeoutSeconds: 5
  config:
    phpMemoryLimit: 256M
    phpUploadMaxFileSize: 500M
    phpPostMaxSize: 500M
    xDebugIp: 127.0.0.1
    elasticsearchCluster: elasticsearch
    elasticsearchServiceName: aws-es-proxy-service
  dbSecretName: drupal-rds
  s3:
    secretName: drupal-s3
    region: eu-west-2
    cname: ''
    cnameIsBucket: false

volumes:
  - name: apache-cache
    emptyDir: {}

imagePullSecrets: [] # Are we using ECR?

podSecurityContext:
  fsGroup: 33

securityContext:
  # TODO: add back in but retain CHOWN, UID and GID capabilities
  # capabilities:
  #   drop:
  #   - ALL
  runAsNonRoot: true
  runAsUser: 33
  runAsGroup: 33

resources: {}

affinity: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  tlsEnabled: true
  path: "/"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    # nginx.ingress.kubernetes.io/modsecurity-snippet: |
    #   Include /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf
    #   SecRuleEngine On
    # Allow traffic coming from: Primary DP Egress, Secondary DP Egress, Studio (Sheffield), DSD VPN, Quantum (x3 ranges), Lucas Cairns (Home), AWilkie NPR, PCotton WLI
    # nginx.ingress.kubernetes.io/whitelist-source-range: 18.130.83.42/32,52.56.168.163/32,217.33.148.210/29,81.134.202.29/32,212.137.36.230/32,62.25.109.197/32,195.92.38.16/28,188.210.212.86/32,217.39.64.119/32,194.33.196.89/32
    nginx.ingress.kubernetes.io/server-snippet: |
       add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";
    nginx.ingress.kubernetes.io/proxy-body-size: 500m

cron:
  schedule: "*/5 * * * *"
  image:
    repository: curlimages/curl
    tag: 7.71.1
