ingress:
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: prisoner-content-hub-backend-ingress-prisoner-content-hub-production-green
  hosts:
    - host: manage.content-hub.prisoner.service.justice.gov.uk
      cert_secret: prisoner-content-hub-cms-certificate
    - host: cms-prisoner-content-hub-production.apps.live.cloud-platform.service.justice.gov.uk
  jsonapi:
    annotations:
      external-dns.alpha.kubernetes.io/set-identifier: prisoner-content-hub-backend-jsonapi-ingress-prisoner-content-hub-production-green
    hosts:
      - host: jsonapi-cms-prisoner-content-hub-production.apps.live.cloud-platform.service.justice.gov.uk

application:
  analyticsSiteId: G-HT9ZQLTDTH

dbBackup:
  enabled: true
dbRefresh:
  enabled: false
s3Sync:
  enabled: false

generic-prometheus-alerts:
  alertSeverity: hmpps-launchpad
