image:
  pullPolicy: Always

ingress:
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: prisoner-content-hub-backend-prisoner-content-hub-development-green
  host: cms-prisoner-content-hub-development.apps.live.cloud-platform.service.justice.gov.uk
  jsonapi:
    annotations:
      external-dns.alpha.kubernetes.io/set-identifier: prisoner-content-hub-backend-jsonapi-prisoner-content-hub-development-green
    host: jsonapi-cms-prisoner-content-hub-development.apps.live.cloud-platform.service.justice.gov.uk
