apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "prisoner-content-hub-backend.fullname" . }}-drupal-cron
  labels:
    {{- include "prisoner-content-hub-backend.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cron.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          containers:
          - name: drupal-cron-job
            {{- with .Values.cron.image }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            command: ["drush", "cron"]
{{ include "drupal-deployment.envs" . | nindent 12 }}
          restartPolicy: OnFailure
