---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    {{- include "prisoner-content-hub-backend.labels" . | nindent 4 }}
  name: {{ include "prisoner-content-hub-backend.fullname" . }}-search-indexing-job
spec:
  groups:
  - name: kubernetes-apps
    rules:
    - alert: {{ include "prisoner-content-hub-backend.fullname" . }}-search-indexing-job-failed-alert
      annotations:
        message: drupal search indexing cron job has failed
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubejobfailed
      expr: kube_job_status_failed{namespace="{{ .Release.Namespace }}",job_name=~"{{ include "prisoner-content-hub-backend.fullname" . }}-search-indexing-[0-9]*"} > 0
      for: 1m
      labels:
        severity: TODO
