{{- if .Values.databaseBackup.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-backup-script
  labels:
    {{- include "prisoner-content-hub-backend.labels" . | nindent 4 }}
data:
  entrypoint.sh: |-
{{ .Files.Get "database-backup.sh" | indent 4 }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "prisoner-content-hub-backend.fullname" . }}-database-backup-cronjob
  labels:
    {{- include "prisoner-content-hub-backend.labels" . | nindent 4 }}
spec:
  schedule: "0 4 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          containers:
          - name: database-backup-cronjob
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            args: ["--target database-refresh-build"]
            command:
              - /bin/entrypoint.sh
            volumeMounts:
              - name: database-refresh-script
                mountPath: /bin/entrypoint.sh
                readOnly: true
                subPath: entrypoint.sh
{{ include "drupal-deployment.envs" . | nindent 12 }}
              - name: DATABASE_BACKUP_S3_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.application.s3.secretName }}
                    key: access_key_id
              - name: DATABASE_BACKUP_S3_SECRET
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.application.s3.secretName }}
                    key: secret_access_key
              - name: DATABASE_BACKUP_S3_REGION
                value: {{ .Values.application.s3.region }}
              - name: DATABASE_BACKUP_S3_BUCKET
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.application.s3.secretName }}
                    key: bucket_name
          restartPolicy: Never
  {{- end }}
