{{- if .Values.dbRefresh.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-refresh-script
  labels:
    {{- include "prisoner-content-hub-backend.labels" . | nindent 4 }}
data:
  entrypoint.sh: |-
{{ .Files.Get "../db-refresh.sh" | indent 4 }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "prisoner-content-hub-backend.fullname" . }}-db-refresh-cronjob
  labels:
    {{- include "prisoner-content-hub-backend.labels" . | nindent 4 }}
spec:
  schedule: "0 4 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      # Tidy up all jobs after 4 days
      ttlSecondsAfterFinished: 345600
      backoffLimit: 0
      activeDeadlineSeconds: 2400
      template:
        spec:
          containers:
          - name: db-refresh-cronjob
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            command:
              - /bin/entrypoint.sh
            volumeMounts:
              - name: db-refresh-script
                mountPath: /bin/entrypoint.sh
                readOnly: true
                subPath: entrypoint.sh
{{ include "drupal-deployment.envs" . | nindent 12 }}
              - name: DB_BACKUP_S3_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.application.s3.secretName }}
                    key: access_key_id
              - name: DB_BACKUP_S3_SECRET
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.application.s3.secretName }}
                    key: secret_access_key
              - name: DB_BACKUP_S3_REGION
                value: {{ .Values.application.s3.region }}
              - name: DB_BACKUP_S3_BUCKET
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.application.s3.secretName }}
                    key: bucket_name
          restartPolicy: Never
          volumes:
            - name: db-refresh-script
              configMap:
                name: db-refresh-script
                defaultMode: 0755
  {{- end }}
