apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "prisoner-content-hub-backend.fullname" . }}-drupal-post-install-hook
  labels:
    {{- include "prisoner-content-hub-backend.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"

spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
  {{ if .Values.dbRefresh.enabled }}
      initContainers:
        - name: db-refresh
          image: "ghcr.io/ministryofjustice/hmpps-mysql-tools:latest"
          command:
            - /bin/entrypoint.sh
          volumeMounts:
            - name: db-refresh-script
              mountPath: /bin/entrypoint.sh
              readOnly: true
              subPath: entrypoint.sh
{{ include "db-backup.envs" . | nindent 10 }}
      volumes:
        - name: db-refresh-script
          configMap:
            name: db-refresh-script
            defaultMode: 0755
  {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["make", "deploy"]
{{ include "drupal-deployment.envs" . | nindent 10 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
