{{- if .Values.ingress.enabled -}}
{{- $fullName := include "prisoner-content-hub-backend.fullname" . -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-jsonapi
  labels:
    {{- include "prisoner-content-hub-backend.labels" . | nindent 4 }}
  {{- with .Values.ingress.jsonapi.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ include "app.joinListWithComma" .Values.ingress.jsonapi.allowed | quote }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.jsonapi.host }}
      {{ if .Values.ingress.jsonapi.cert_secret }}secretName: {{ .Values.ingress.jsonapi.cert_secret }}{{ end }}
  rules:
    - host: {{ .Values.ingress.jsonapi.host | quote }}
      http:
        paths:
          - path: "/"
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
  {{- end -}}
