{{- $hashSalt := (randAlphaNum 128) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "prisoner-content-hub-backend.fullname" . }}
  labels:
    {{- include "prisoner-content-hub-backend.labels" . | nindent 4 }}
data:
  hashSalt: {{ default $hashSalt .Values.hashSalt | b64enc }}
