apiVersion: v1
kind: Service
metadata:
  name: drupal-service
  labels:
    {{- include "drupal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "drupal.selectorLabels" . | nindent 4 }}
