---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prisoner-content-hub-backend.fullname" . }}
  labels:
    {{- include "prisoner-content-hub-backend.labels" . | nindent 4 }}-varnish
spec:
  selector:
    {{- include "prisoner-content-hub-backend.selectorLabels" . | nindent 4 }}-varnish
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: varnish-configmap
  labels:
    app: varnish
data:
  default.vcl: |-
{{ .Files.Get "default.vcl" | indent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: varnish-deployment
  labels:
    {{- include "prisoner-content-hub-backend.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "prisoner-content-hub-backend.selectorLabels" . | nindent 6 }}-varnish
  template:
    metadata:
      labels:
        {{- include "prisoner-content-hub-backend.selectorLabels" . | nindent 8 }}-varnish
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 102
      containers:
        - name: varnish
          image: varnish:7.1.2
          env:
            - name: CACHE_SIZE
              value: 128m
            - name: VCL_CONFIG
              value: /etc/varnish/configmap/default.vcl
          volumeMounts:
            - name: varnish-config
              mountPath: /etc/varnish/configmap
          ports:
            - containerPort: 80
      volumes:
        - name: varnish-config
          configMap:
            name: varnish-configmap
